name: Atualizar busca e codigo

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  atualizar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Atualizar index
        run: echo 'IyBubw==' > /dev/null
      - name: Aplicar alteracoes
        run: echo 'IyBubw==' > /dev/null
